server:
  port: "8080"
  base_url: "http://192.168.1.119:8080"

apprise:
  url: "http://apprise:8000"
  tags:
    - releases

defaults:
  fetch_interval: "1h"
  alert_keywords:
    - "breaking"
    - "breaking change"
    - "security"
    - "warning"
    - "deprecated"

feeds:
  - name: "LoggiFly"
    url: "https://github.com/clemcer/LoggiFly/releases.atom"
    fetch_interval: "30m"
    image: "loggify.webp"
    sections:
      mode: include
      names:
        - "what's new"
        - "bug fixes"
        - "breaking changes"
    alert_keywords:
      - "breaking"
      - "security"

  - name: "Hyprland"
    url: "https://github.com/hyprwm/Hyprland/releases.atom"
    image: "hyprland.webp"
    sections:
      mode: exclude
      names:
        - "special thanks"
        - "donators"
        - "contributors"
        - "one-time donators"
        - "sponsors"
        - "supporters"

  - name: "Vaultwarden"
    url: "https://github.com/dani-garcia/vaultwarden/releases.atom"
    image: "vaultwarden.webp"
    raw: true