on:
  workflow_dispatch:

jobs:
  build:
    runs-on: docker

    container:
      image: docker:24-cli
    services:
      docker:
        image: docker:24-dind
        options: --privileged
        env:
          DOCKER_TLS_CERTDIR: ""

    env:
      DOCKER_HOST: tcp://localhost:2375

    steps:
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y git bash curl

      - name: Clone repository
        run: git clone https://git.balgeriada.com/balgerion/releasefeed.git .

      - name: Build and push Docker image
        run: |
          docker info
          docker buildx create --use || true
          docker buildx build \
            -t git.balgeriada.com/balgerion/releasefeed:latest \
            --push .