server:
  port: "880"
  base_url: "https://feed.balgeriada.com"

apprise:
  url: "https://notify.balgeriada.com/cfg/e92e76571d74be82dd94439258115f051b0f0d4c619835b3bd385149174dc281"
  tags:
    - releases

defaults:
  fetch_interval: "1h"
  alert_keywords:
    - "breaking"
    - "breaking change"
    - "security"
    - "warning"
    - "deprecated"
  exclude_sections:
    - "special thanks"
    - "sponsors"
    - "donators"
    - "contributors"
    - "one-time donators"
    - "supporters"

feeds:
  - name: "LoggiFly"
    url: "https://github.com/clemcer/LoggiFly/releases.atom"
    fetch_interval: "30m"
    image: "loggify.webp"

  - name: "Hyprland"
    url: "https://github.com/hyprwm/Hyprland/releases.atom"
    image: "hyprland.svg"

  - name: "Vaultwarden"
    url: "https://github.com/dani-garcia/vaultwarden/releases.atom"
    image: "vaultwarden.webp"
    notify_all: true
    ignore_titles:
      - "beta"
      - "-rc"